services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    hostname: ${TS_HOSTNAME}
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=${TS_EXTRA_ARGS}
    volumes:
      - /mnt/m2/docker/tailscale/state:/var/lib/tailscale
    restart: unless-stopped