services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale-exit
    hostname: ts-exit
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=${TS_EXTRA_ARGS}
      - TS_TUN_MODE=tun
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /mnt/m2/docker/tailscale-isolated/state:/var/lib/tailscale
    restart: unless-stopped
